"""empty message

Revision ID: c276fddee0c0
Revises: c5c10007960c
Create Date: 2019-11-16 20:59:36.007205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c276fddee0c0'
down_revision = 'c5c10007960c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('telephone', sa.String(length=50), nullable=False))
    op.drop_column('profiles', 'telephon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('telephon', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'telephone')
    # ### end Alembic commands ###
