"""empty message

Revision ID: c5c10007960c
Revises: 814522b75445
Create Date: 2019-11-16 20:59:13.957218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c10007960c'
down_revision = '814522b75445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('telephon', sa.String(length=50), nullable=False))
    op.drop_column('profiles', 'telephone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('telephone', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('profiles', 'telephon')
    # ### end Alembic commands ###
